### ISSUE TITLE
Disable "Import As New"?

### ISSUE THREAD

**Issue by copyaplexy** [benwinding/react-admin-import-csv#18]
I have an app where users should not be able to create new records - only update existing records.

I tried to find a way to disable the `Import As New` feature using `REF`s but wasn't able to.

Is there an easier way to do what I want to do here?

**Comment by benwinding** [comment]
Hi @copyaplexy,

In `react-admin-import-csv@0.2.17` You can now disable "Import As New" button from the configuration options:

``` jsx
const config = {
  disableImportNew: true
}
<ImportButton {...props} {...config}/>
```

[Full list of options here](https://github.com/benwinding/react-admin-import-csv#configuration-options)

Cheers,
Ben

**Comment by copyaplexy** [comment]
@benwinding This is great! Thanks man!

**Comment by fkowal** [comment]
Hey is this flag supported?

As far as i can tell it's only used in the type definition and the README

so since' it's not actually used in the implementation I don't see a way for it to be used


Here is something I tried

```
const config: ImportConfig = {...
preCommitCallback: (action, values) => {if(action =='create') return [] else return values}
}...
```

but the issue here is that the https://github.com/benwinding/react-admin-import-csv/blob/79fe1f498ae02872d0437d5273e7931d8c705285/src/uploader.ts#L15

proceeds calling the dataProvider with an empty array

that causes a bad request (which makes sense) because the request is something like create nothing 



another question I have related to `create`

```
  const shouldReject =
    !postCommitCallback && reportItems.some((r) => !r.success);
  if (shouldReject) {
    return Promise.reject(reportItems.map((r) => r.response));
  }
 <-- what happens when here ?
```

if I pass `postCommitCallback` config we not return anything
doesn't that cause async await issue?

next question:
```
  const reportItems = await createInDataProvider(
    logging,
    dataProvider,
    resource,
    parsedValues
  );
  if (postCommitCallback) {
    postCommitCallback(reportItems); <- here the postCommitCallback
  }

const shouldReject =
    !postCommitCallback <- if this hook would give control to the user I could recover from the above error
```

the postCommitCallback is called both by `create` and `update` so there is no way to telling by with one as in `preCommitCallback`

also the `preCommitCallback` give control to the use and the `postCommitCallback` doesn't

**Comment by benwinding** [comment]
Hi @fkowal,

The latest deploy should re-enable the flags `disableImportNew`, `disableImportOverwrite` (they we're forgotton during a recent refactor).

> Here is something I tried
```
const config: ImportConfig = {...
preCommitCallback: (action, values) => {if(action =='create') return [] else return values}
}...
```
That is expected behaviour, the `preCommitCallback` is for transforming data. If you want to validate data then use the  `validateRow` function.

> if I pass postCommitCallback config we not return anything doesn't that cause async await issue?

Yes that may cause an issue, I suggest using the `validateRow` function to selectively return things.

In the future, please don't ask a bunch of unrelated questions on an old issue it's annoying to manage. Please try and keep the issue focused and open a new one if necessary.

Cheers,
Ben
